services:
  postgres:
    image: postgres:16-alpine
    container_name: pet-store-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: petstore
      POSTGRES_PASSWORD: petstore
      POSTGRES_DB: petstore
    ports:
      - "5432:5432"
    volumes:
      - pet-store-db:/var/lib/postgresql/data

volumes:
  pet-store-db:
